const path = require('path');
const webpack = require('webpack');
const WrapperPlugin = require('wrapper-webpack-plugin');

module.exports = {
  target: 'node',
  devtool: false,

  entry: {
    script: [path.resolve(__dirname, '..', 'scripts', 'src', 'index.js')],
  },

  output: {
    libraryTarget: 'commonjs',
    globalObject: 'this',
    path: path.resolve(__dirname, '..', 'scripts', 'dist'),
    filename: 'script.js',
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,

        use: {
          loader: 'babel-loader',
        },
      },
    ],
  },

  plugins: [
    new WrapperPlugin({
      test: /\.js$/,

      header: `/**!
   ***           <WARNING>             ***
   *   DO NOT EDIT THIS FILE DIRECTLY.   *
   *  IT WILL BE OVERWRITTEN BY WEBPACK. *
   *    YOU WILL LOSE THESE CHANGES.     *
   *     NEVER PUBLISH THIS SCRIPT.      *
   *   BUILD IT FOR PRODUCTION FIRST.    *
   ***          </WARNING>             ***
*/

const module = { exports: {} };
const exports = {};

`,
    }),
  ],

  externals: [
    new RegExp(
      [
        'Animation',
        'Audio',
        'CameraInfo',
        'DeepLink',
        'DeviceMotion',
        'Diagnostics',
        'FaceGestures',
        'FaceTracking2D',
        'FaceTracking',
        'Fonts',
        'HandTracking',
        'Instruction',
        'IrisTracking',
        'LightingEstimation',
        'LiveStreaming',
        'Locale',
        'Materials',
        'NativeUI',
        'Networking',
        'Patches',
        'Persistence',
        'PersonSegmentation',
        'Random',
        'Reactive',
        'Scene',
        'Shaders',
        'Svgs',
        'Textures',
        'Time',
        'TouchGestures',
        'Units',
      ].join('|'),
    ),
  ]
};
